name: EasyService
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.4
  flutter_native_splash: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/splash_tv.png

# ---------------- SPLASH SCREEN ----------------
flutter_native_splash:
  color: "#87CEEB"   # Sky Blue Background
  image: assets/splash_tv.png
  android: true
  ios: true

# ---------------- APP ICON ----------------
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/splash_tv.png"
